version: '3'
services:
  todo_backend:
    container_name: todo_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-mongo
      - db-redis
    ports:
      - "3000:3000"
    command: ["serverless", "offline", "--host", "0.0.0.0"]
    environment:
      - REDIS_HOST=db-redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@db-mongo:27017/
      - MONGO_DB=${MONGO_DB}
  db-mongo:
    restart: always
    image: mongo
    container_name: todo_db_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  db-redis:
    restart: always
    image: redis
    container_name: todo_db_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
